### ISSUE TITLE
PTP Timing?

### ISSUE THREAD

**Issue by HeroesLament** [AllStarLink/voter#10]
Opening this issue to broach the idea of synchronizing timing via PTP rather than a direct GPS reciever. The ptp4l is included in most distributions now, and seems like a novel solution to requiring a GPS receiver at each site if PTP clock synchronization is possible. 

Thoughts anyone?

**Comment by ve7fet** [comment]
The VOTER/RTCM is an embedded hardware device, running assembly code. It does not run higher level software such as Linux, therefore has no support for any higher level applications, such as ptp4l.
