### ISSUE TITLE
Supporting DMR Simulcast?

### ISSUE THREAD

**Issue by HeroesLament** [AllStarLink/voter#11]
Broaching the question of supporting DMR Simulcast in addition to Analog FM voice.

Thoughts from the maintainers?

**Comment by ve7fet** [comment]
Not possible with the current hardware.

The current hardware digitizes analog speech by sampling it at 8000 samples/sec, and recording a voltage level, to turn into a bit stream (thereby creating a PCM audio stream/packet). That voice packet is set to the host. 

At the same time, out-of-band noise is sent to a rectifier to create a DC voltage that corresponds to how "quiet" and therefor how strong the signal is (RSSI). This too is then sent to the host.

The host manages all the incoming voice packets from all the receivers, then uses the RSSI that each one of them sent with the voice packet, to determine which one is the "best", and sends that to the transmitter(s).

DMR is not analog voice, it is already a digital stream of data containing voice and other overhead bits. So, it is not just a matter of sampling audio and figuring out the RSSI. You would need to have framing and clock recovery on the received signal to figure out where the data frames are, then do some sort of BER calculation on those frames, and then figure out what frames had the lowest BER, and re-assemble a data stream to send to the transmitter(s).

In addition to that, somehow you have to get Asterisk to decode/recode the data into actual voice along the way.

This is a entirely much more complex implementation, and is beyond the scope of this project in many ways.
