### ISSUE TITLE
ADPCM code removal?

### ISSUE THREAD

**Issue by ve7fet** [AllStarLink/voter#5]
In reviewing the code, it appears that the default audio audio encode/decode is ulaw, if options are undefined in voter.conf. 

To use ADPCM, you have to specifically configure the client in voter.conf to use ADPCM, so that option will be passed over the UDP stream to the client and set an option flag. Not that you would want to, as ADPCM appears to 4-bit audio, and ulaw is 8-bit... more bits, more better! There is also an undocumented nulaw in chan_voter (and voter.conf), but it does not appear that the VOTER/RTCM would know what to do with that.

It may be worth considering removing the ADPCM code to free up more space in the PIC, as I don’t think anyone would really want to use it to make their audio sound worse! That would require some graceful handling if someone tries to configure chan_voter to use ADPCM, and we no longer support it.

Requires further investigation and discussion.

**Comment by tsawyer** [comment]
The attached file has comments which document some of the items you mention. ADPCM may be desirable for very low bandwidth applications. My take is ADPCM should remain in the code or at least provide a release with ADPCM.

[voter.conf.dpkg-dist.zip](https://github.com/AllStarLink/Voter/files/7971780/voter.conf.dpkg-dist.zip)

**Comment by ve7fet** [comment]
Valid concern. We can leave the code where it is!

Thanks for the comments on the voter.conf options. I will roll those in to the wiki as I am cleaning up all the rest of the related documentation.
